@extends('layouts.app', ['title' => 'SiswaSphere | Member sign in'])

@section('content')
    @php
        $emailInvalid = $errors->has('email');
        $passwordInvalid = $errors->has('password');
    @endphp
    <section class="mx-auto grid max-w-5xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm lg:grid-cols-[0.9fr_1.1fr]">
        <div class="bg-blue-700 p-7 text-white sm:p-10 lg:p-12"><div class="flex h-12 w-12 items-center justify-center rounded-xl bg-white text-sm font-bold tracking-wide text-blue-700">SS</div><p class="mt-10 text-sm font-semibold text-blue-100">Pembimbing Rakan Siswa</p><h1 class="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Your PRS community, in one place.</h1><p class="mt-4 max-w-sm text-sm leading-6 text-blue-100">Keep up with your profile, committee role, meetings, and activities through your SiswaSphere member portal.</p><div class="mt-10 border-t border-blue-400/40 pt-6"><p class="text-sm font-semibold text-white">Need organization information?</p><a href="{{ route('directory') }}" class="mt-2 inline-flex text-sm font-semibold text-blue-100 underline decoration-blue-300 underline-offset-4 hover:text-white">Explore the PRS directory</a></div></div>
        <div class="p-7 sm:p-10 lg:p-12"><p class="text-sm font-semibold text-blue-700">Member sign in</p><h2 class="mt-2 text-2xl font-bold tracking-tight text-slate-900">Welcome back</h2><p class="mt-2 text-sm leading-6 text-slate-600">Use the email and password assigned with your PRS membership.</p><form method="POST" action="{{ route('member.authenticate') }}" class="mt-8 space-y-5">@csrf<div><label for="email" class="ui-label">Email address</label><input id="email" type="email" name="email" value="{{ old('email') }}" required autocomplete="email" aria-invalid="{{ $emailInvalid ? 'true' : 'false' }}" aria-describedby="{{ $emailInvalid ? 'email-help email-error' : 'email-help' }}" class="{{ $emailInvalid ? 'ui-input border-red-500 focus:border-red-500 focus:ring-red-500/20' : 'ui-input' }}" placeholder="name@upsi.edu.my"><p id="email-help" class="ui-help-text">Use the email registered to your member profile.</p>@error('email')<p id="email-error" class="ui-error-text" role="alert">{{ $message }}</p>@enderror</div><div><label for="password" class="ui-label">Password</label><input id="password" type="password" name="password" required autocomplete="current-password" aria-invalid="{{ $passwordInvalid ? 'true' : 'false' }}" class="{{ $passwordInvalid ? 'ui-input border-red-500 focus:border-red-500 focus:ring-red-500/20' : 'ui-input' }}">@error('password')<p class="ui-error-text" role="alert">{{ $message }}</p>@enderror</div><button type="submit" class="ui-button-primary w-full">Sign in to member portal</button></form><div class="mt-8 border-t border-slate-200 pt-6"><p class="text-sm text-slate-600">Administrator? <a href="{{ route('admin.login') }}" class="font-semibold text-blue-700 hover:text-blue-800 hover:underline">Go to admin sign in</a>.</p></div></div>
    </section>
@endsection
