@extends('layouts.app', ['title' => 'PRS NEXUS | Admin dashboard'])

@section('content')
    <section class="flex flex-col gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-end sm:justify-between">
        <div>
            <p class="text-sm font-semibold text-blue-700">Admin dashboard</p>
            <h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">Welcome back, {{ $admin?->name ?? 'Administrator' }}</h1>
            <p class="mt-2 max-w-2xl text-sm leading-6 text-slate-600">A focused overview of the PRS community and its upcoming work.</p>
        </div>
        <a href="{{ route('admin.members.create') }}" class="ui-button-primary w-full sm:w-auto">Add member</a>
    </section>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach (['Members' => $stats['members'], 'Committee positions' => $stats['committees'], 'Meetings' => $stats['meetings'], 'Activities' => $stats['activities']] as $label => $value)
            <x-card><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-bold tracking-tight text-slate-900">{{ $value }}</p></x-card>
        @endforeach
    </section>

    <section class="mt-8 grid gap-6 xl:grid-cols-2">
        <x-card><div class="flex items-center justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Schedule</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Upcoming meetings</h2></div><a href="{{ route('admin.meetings.index') }}" class="text-sm font-semibold text-blue-700 hover:underline">Manage meetings</a></div><div class="mt-5 divide-y divide-slate-200">@forelse($upcomingMeetings as $meeting)<article class="py-3 first:pt-0 last:pb-0"><p class="font-semibold text-slate-900">{{ $meeting->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $meeting->meeting_date->format('d M Y') }} &middot; {{ $meeting->location ?: 'Venue to be confirmed' }}</p></article>@empty<x-empty-state title="No upcoming meetings" description="Schedule a meeting when the next PRS session is confirmed."><a href="{{ route('admin.meetings.create') }}" class="ui-button-secondary">Schedule meeting</a></x-empty-state>@endforelse</div></x-card>
        <x-card><div class="flex items-center justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Engagement</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Recent activities</h2></div><a href="{{ route('admin.activities.index') }}" class="text-sm font-semibold text-blue-700 hover:underline">Manage activities</a></div><div class="mt-5 divide-y divide-slate-200">@forelse($recentActivities as $activity)<article class="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0"><div><p class="font-semibold text-slate-900">{{ $activity->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $activity->activity_date->format('d M Y') }} &middot; {{ $activity->location ?: 'Venue to be confirmed' }}</p></div><x-badge :variant="$activity->status === 'completed' ? 'success' : ($activity->status === 'ongoing' ? 'info' : 'upcoming')">{{ ucfirst($activity->status) }}</x-badge></article>@empty<x-empty-state title="No activities recorded" description="Add an activity to start sharing PRS engagement opportunities."><a href="{{ route('admin.activities.create') }}" class="ui-button-secondary">Add activity</a></x-empty-state>@endforelse</div></x-card>
    </section>

    <section class="mt-8 grid items-stretch gap-6 xl:grid-cols-2">
        <x-card class="h-full"><div class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Organization</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Recently added members</h2></div><a href="{{ route('admin.members.index') }}" class="shrink-0 text-sm font-semibold text-blue-700 hover:underline">View All Members &rarr;</a></div><div class="mt-5 divide-y divide-slate-200">@forelse($members->take(5) as $member)<article class="flex items-center gap-3 py-3 first:pt-0 last:pb-0"><x-member-avatar :member="$member" size="h-12 w-12" /><div class="min-w-0 flex-1"><p class="truncate font-semibold text-slate-900">{{ $member->full_name }}</p><p class="mt-0.5 truncate text-sm text-slate-500">{{ $member->display_role }}</p><p class="mt-1 text-xs text-slate-400">Joined {{ $member->created_at->diffForHumans() }}</p></div><x-badge :variant="$member->status === 'active' ? 'active' : 'inactive'">{{ ucfirst($member->status) }}</x-badge></article>@empty<x-empty-state title="No members recorded" description="Add the first PRS member to begin building the directory."><a href="{{ route('admin.members.create') }}" class="ui-button-secondary">Add member</a></x-empty-state>@endforelse</div></x-card>
        <x-card class="h-full"><div><p class="text-sm font-semibold text-blue-700">Quick actions</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Common admin tasks</h2><p class="mt-1 text-sm text-slate-500">Create and maintain the records that keep PRS up to date.</p></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><a href="{{ route('admin.members.create') }}" class="rounded-lg border border-slate-200 p-4 transition hover:border-blue-200 hover:bg-blue-50"><p class="font-semibold text-slate-900">Add member</p><p class="mt-1 text-sm text-slate-500">Create a profile and portal access.</p></a><a href="{{ route('admin.meetings.create') }}" class="rounded-lg border border-slate-200 p-4 transition hover:border-blue-200 hover:bg-blue-50"><p class="font-semibold text-slate-900">Create meeting</p><p class="mt-1 text-sm text-slate-500">Add a PRS schedule item.</p></a><a href="{{ route('admin.activities.create') }}" class="rounded-lg border border-slate-200 p-4 transition hover:border-blue-200 hover:bg-blue-50"><p class="font-semibold text-slate-900">Create activity</p><p class="mt-1 text-sm text-slate-500">Publish an engagement update.</p></a><a href="{{ route('admin.committee-positions.create') }}" class="rounded-lg border border-slate-200 p-4 transition hover:border-blue-200 hover:bg-blue-50"><p class="font-semibold text-slate-900">Create committee position</p><p class="mt-1 text-sm text-slate-500">Maintain leadership roles.</p></a></div></x-card>
    </section>
@endsection
