@extends('layouts.app', ['title' => 'SiswaSphere | Admin dashboard'])

@section('content')
    <section class="flex flex-col gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:flex-row sm:items-end sm:justify-between">
        <div>
            <p class="text-sm font-semibold text-blue-700">Admin dashboard</p>
            <h1 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">Welcome back, {{ $admin?->name ?? 'Administrator' }}</h1>
            <p class="mt-2 max-w-2xl text-sm leading-6 text-slate-600">A focused overview of the PRS community and its upcoming work.</p>
        </div>
        <a href="{{ route('admin.members.create') }}" class="ui-button-primary w-full sm:w-auto">Add member</a>
    </section>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach (['Members' => $stats['members'], 'Committee positions' => $stats['committees'], 'Meetings' => $stats['meetings'], 'Activities' => $stats['activities']] as $label => $value)
            <x-card><p class="text-sm font-medium text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-bold tracking-tight text-slate-900">{{ $value }}</p></x-card>
        @endforeach
    </section>

    <section class="mt-8"><div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-blue-700">Quick actions</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Choose your next task</h2></div></div><div class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><a href="{{ route('admin.members.create') }}" class="ui-card p-4 hover:border-blue-200 hover:shadow-md"><p class="font-semibold text-slate-900">Add a member</p><p class="mt-1 text-sm text-slate-500">Create a profile and portal access.</p></a><a href="{{ route('admin.committee-positions.create') }}" class="ui-card p-4 hover:border-blue-200 hover:shadow-md"><p class="font-semibold text-slate-900">Set committee roles</p><p class="mt-1 text-sm text-slate-500">Maintain PRS leadership positions.</p></a><a href="{{ route('admin.meetings.create') }}" class="ui-card p-4 hover:border-blue-200 hover:shadow-md"><p class="font-semibold text-slate-900">Schedule a meeting</p><p class="mt-1 text-sm text-slate-500">Record meeting details for members.</p></a><a href="{{ route('admin.activities.create') }}" class="ui-card p-4 hover:border-blue-200 hover:shadow-md"><p class="font-semibold text-slate-900">Add an activity</p><p class="mt-1 text-sm text-slate-500">Publish a PRS activity update.</p></a></div></section>

    <section class="mt-8 grid gap-6 xl:grid-cols-2">
        <x-card><div class="flex items-center justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Schedule</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Upcoming meetings</h2></div><a href="{{ route('admin.meetings.index') }}" class="text-sm font-semibold text-blue-700 hover:underline">Manage meetings</a></div><div class="mt-5 divide-y divide-slate-200">@forelse($upcomingMeetings as $meeting)<article class="py-3 first:pt-0 last:pb-0"><p class="font-semibold text-slate-900">{{ $meeting->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $meeting->meeting_date->format('d M Y') }} · {{ $meeting->location ?: 'Venue to be confirmed' }}</p></article>@empty<x-empty-state title="No upcoming meetings" description="Schedule a meeting when the next PRS session is confirmed."><a href="{{ route('admin.meetings.create') }}" class="ui-button-secondary">Schedule meeting</a></x-empty-state>@endforelse</div></x-card>
        <x-card><div class="flex items-center justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Engagement</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Recent activities</h2></div><a href="{{ route('admin.activities.index') }}" class="text-sm font-semibold text-blue-700 hover:underline">Manage activities</a></div><div class="mt-5 divide-y divide-slate-200">@forelse($recentActivities as $activity)<article class="flex items-start justify-between gap-4 py-3 first:pt-0 last:pb-0"><div><p class="font-semibold text-slate-900">{{ $activity->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $activity->activity_date->format('d M Y') }} · {{ $activity->location ?: 'Venue to be confirmed' }}</p></div><x-badge :variant="$activity->status === 'completed' ? 'success' : ($activity->status === 'ongoing' ? 'info' : 'upcoming')">{{ ucfirst($activity->status) }}</x-badge></article>@empty<x-empty-state title="No activities recorded" description="Add an activity to start sharing PRS engagement opportunities."><a href="{{ route('admin.activities.create') }}" class="ui-button-secondary">Add activity</a></x-empty-state>@endforelse</div></x-card>
    </section>

    <section class="mt-8"><div class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-blue-700">Organization</p><h2 class="mt-1 text-xl font-semibold text-slate-900">Recently added members</h2></div><a href="{{ route('admin.members.index') }}" class="text-sm font-semibold text-blue-700 hover:underline">Manage members</a></div><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($members as $member)<x-card><div class="flex items-center gap-3"><x-member-avatar :member="$member" size="md" /><div class="min-w-0"><p class="truncate font-semibold text-slate-900">{{ $member->full_name }}</p><p class="mt-1 truncate text-sm text-slate-500">{{ $member->display_role }}</p></div></div></x-card>@empty<x-empty-state class="md:col-span-2 xl:col-span-3" title="No members recorded" description="Add the first PRS member to begin building the directory."><a href="{{ route('admin.members.create') }}" class="ui-button-secondary">Add member</a></x-empty-state>@endforelse</div></section>
@endsection
