@extends('layouts.app', ['title' => 'PRS NEXUS | Integrated Peer Management and Support System'])

@section('content')
    <section class="grid overflow-hidden rounded-2xl bg-blue-700 text-white shadow-sm lg:grid-cols-[1.15fr_0.85fr]">
        <div class="p-7 sm:p-10 lg:p-14"><p class="text-sm font-semibold text-blue-100">Pembimbing Rakan Siswa · UPSI</p><h1 class="mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">A stronger student community starts with connection.</h1><p class="mt-5 max-w-2xl text-base leading-7 text-blue-100">Discover the people, leadership, meetings, and activities that support PRS students in building confidence, wellbeing, and campus community.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('directory') }}" class="inline-flex items-center justify-center rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-blue-700 shadow-sm transition hover:bg-blue-50">Explore PRS directory</a><a href="#about" class="inline-flex items-center justify-center rounded-lg border border-blue-300 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-600">Learn about PRS</a></div></div>
        <div class="flex items-center bg-blue-600/40 p-7 sm:p-10 lg:p-12"><div class="w-full rounded-2xl border border-blue-300/40 bg-white/10 p-6"><p class="text-sm font-medium text-blue-100">PRS at a glance</p><dl class="mt-5 space-y-4">@foreach($stats as $label => $value)<div class="flex items-end justify-between border-b border-blue-300/30 pb-4 last:border-0 last:pb-0"><dt class="text-sm text-blue-100">{{ ucfirst(str_replace('_', ' ', $label)) }}</dt><dd class="text-3xl font-bold">{{ $value }}</dd></div>@endforeach</dl></div></div>
    </section>

    <section id="about" class="scroll-mt-24 py-12 sm:py-16"><div class="max-w-2xl"><p class="text-sm font-semibold text-blue-700">About PRS</p><h2 class="mt-2 text-3xl font-bold tracking-tight text-slate-900">Peer support that helps students grow.</h2><p class="mt-4 text-base leading-7 text-slate-600">Pembimbing Rakan Siswa is a student peer-support community focused on friendship, leadership, and positive student development. PRS NEXUS makes it easy to discover the people and activities behind that support.</p></div><div class="mt-8 grid gap-4 md:grid-cols-3"><x-card><h3 class="font-semibold text-slate-900">Peer connection</h3><p class="mt-2 text-sm leading-6 text-slate-600">Find familiar faces and supportive PRS members across the university community.</p></x-card><x-card><h3 class="font-semibold text-slate-900">Student leadership</h3><p class="mt-2 text-sm leading-6 text-slate-600">Meet the committee members helping shape a welcoming and active organization.</p></x-card><x-card><h3 class="font-semibold text-slate-900">Meaningful activities</h3><p class="mt-2 text-sm leading-6 text-slate-600">Stay connected with meetings and activities that bring students together.</p></x-card></div></section>

    <section id="community" class="scroll-mt-24 border-t border-slate-200 py-12 sm:py-16"><div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-blue-700">Meet the community</p><h2 class="mt-2 text-2xl font-bold text-slate-900">Featured PRS members</h2></div><a href="{{ route('directory') }}" class="text-sm font-semibold text-blue-700 hover:underline">View all members</a></div><div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@forelse($featuredMembers as $member)<x-card class="flex items-center gap-4"><x-member-avatar :member="$member" size="h-12 w-12" /><div class="min-w-0"><h3 class="truncate font-semibold text-slate-900">{{ $member->full_name }}</h3><p class="mt-1 text-sm text-slate-500">{{ $member->programme ?: 'PRS member' }}</p><p class="mt-2 text-sm font-medium text-blue-700">{{ $member->display_role }}</p></div></x-card>@empty<x-empty-state class="sm:col-span-2 lg:col-span-3" title="No members to feature yet" description="Member profiles will appear here when they are available." />@endforelse</div></section>

    <section class="grid gap-6 border-t border-slate-200 py-12 sm:py-16 lg:grid-cols-2"><div><p class="text-sm font-semibold text-blue-700">Stay informed</p><h2 class="mt-2 text-2xl font-bold text-slate-900">Meetings and activities</h2><p class="mt-3 max-w-md text-sm leading-6 text-slate-600">See what is happening across the PRS community and find an activity that interests you.</p><a href="{{ route('directory') }}" class="mt-5 inline-flex text-sm font-semibold text-blue-700 hover:underline">Browse all records</a></div><div class="grid gap-4 sm:grid-cols-2"><x-card><h3 class="font-semibold text-slate-900">Latest meetings</h3><div class="mt-4 space-y-4">@forelse($latestMeetings as $meeting)<div><p class="font-medium text-slate-900">{{ $meeting->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $meeting->meeting_date->format('d M Y') }} · {{ $meeting->location ?: 'Venue to be confirmed' }}</p></div>@empty<p class="text-sm text-slate-500">No meetings recorded yet.</p>@endforelse</div></x-card><x-card><h3 class="font-semibold text-slate-900">Latest activities</h3><div class="mt-4 space-y-4">@forelse($latestActivities as $activity)<div><p class="font-medium text-slate-900">{{ $activity->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $activity->activity_date->format('d M Y') }} · {{ ucfirst($activity->status) }}</p></div>@empty<p class="text-sm text-slate-500">No activities scheduled yet.</p>@endforelse</div></x-card></div></section>

    <section class="rounded-2xl border border-blue-100 bg-blue-50 p-7 sm:flex sm:items-center sm:justify-between sm:p-10"><div><h2 class="text-2xl font-bold text-slate-900">Ready to explore PRS?</h2><p class="mt-2 text-sm leading-6 text-slate-600">Find a member, committee role, meeting, or upcoming activity.</p></div><a href="{{ route('directory') }}" class="ui-button-primary mt-5 sm:mt-0">Open directory</a></section>
@endsection
